# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a29b2567cc1a1708ab580d7e63b7b64e290c85ed49fc4181e4bf1bd87587512ff7d387501aec7dbe4b8f20dedee3d6e18d9f6bac9ac4c1111e6f205f43167ac

test:
  secret_key_base: e38906d7b15a81b5c1fcb8b5244fa5436c6749860c188ca1ff26e6339703a2e9d7a6913a1665b4352bbddfae35dc1a0058d87e2fb3e25568859c2156f5dbd3d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
